"""empty message

Revision ID: 99db655d6913
Revises: 05cd5308ff5b
Create Date: 2022-06-02 06:30:15.106881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99db655d6913'
down_revision = '05cd5308ff5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.add_column('show', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'show', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'show', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_column('show', 'artist_id')
    op.drop_column('show', 'venue_id')
    # ### end Alembic commands ###
